apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: homepage-downloads-pvc
  namespace: homepage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vsphere-sc
  resources:
    requests:
      storage: 2Gi
